# Generated by Django 4.0 on 2022-07-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutterwave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutterwave',
            name='generated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
