# Generated by Django 4.0 on 2022-06-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-generated',)},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date_created',
            new_name='generated',
        ),
    ]
