# Generated by Django 4.0 on 2022-06-27 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0002_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='generated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
