# Generated by Django 4.0 on 2022-07-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0003_alter_payment_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
