# Generated by Django 4.0 on 2022-07-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0005_alter_payment_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='verified',
        ),
    ]
