# Generated by Django 4.0 on 2022-07-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0006_rename_status_payment_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(blank=True, max_length=3000, null=True),
        ),
    ]
