# Generated by Django 4.0 on 2022-07-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0009_alter_payment_generated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Paystack',
        ),
    ]
