# Generated by Django 4.0 on 2022-07-17 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0010_rename_payment_paystack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystack',
            name='generated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
