# Generated by Django 4.0 on 2022-07-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_user_code'),
        ('paystack', '0011_alter_paystack_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystack',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
    ]
