# Generated by Django 4.0 on 2022-07-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0012_alter_paystack_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystack',
            name='email',
            field=models.EmailField(blank=True, max_length=3000, null=True),
        ),
    ]
