# Generated by Django 4.0 on 2022-07-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_user_code'),
        ('paystack', '0013_alter_paystack_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystack',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
    ]
