# Generated by Django 4.0 on 2022-07-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0014_paystack_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paystack',
            name='user',
        ),
    ]
