# Generated by Django 4.0 on 2022-07-29 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0017_alter_paystack_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystack',
            name='generated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='date_created',
            field=models.DateField(),
        ),
    ]
