# Generated by Django 4.0 on 2022-07-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='vG7JZIW5', max_length=8, null=True, unique=True),
        ),
    ]
