# Generated by Django 4.0 on 2022-11-09 09:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(blank=True, null=True)),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, null=True, size=None)),
                ('returns', models.IntegerField(blank=True, default=0, null=True)),
                ('players', models.IntegerField(blank=True, default=0, null=True)),
                ('time_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_ending', models.DateTimeField(blank=True, null=True)),
                ('ended', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('time_generated',),
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('generatedresult', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, null=True, size=None)),
                ('winning', models.IntegerField(blank=True, null=True)),
                ('selectednumber', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
                ('status', models.CharField(choices=[('won', 'WON'), ('pending', 'PENDING'), ('loss', 'LOSS')], default='pending', max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
        migrations.AlterField(
            model_name='custom',
            name='code',
            field=models.CharField(blank=True, default='s0rkWx7g', max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.custom'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.gameround'),
        ),
    ]
