# Generated by Django 4.0 on 2022-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_result_user_balance_alter_user_code_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='Z8ObU76d', max_length=8, null=True, unique=True),
        ),
    ]
