# Generated by Django 4.0 on 2022-11-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_lotteryround_tickets_delete_duration_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
        migrations.AlterField(
            model_name='custom',
            name='code',
            field=models.CharField(blank=True, default='vTi88DiJ', max_length=8, null=True, unique=True),
        ),
    ]
