# Generated by Django 4.0 on 2022-11-09 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_tickets_ticket_alter_custom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='code',
            field=models.CharField(blank=True, default='00fGtQHw', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.lotteryround'),
        ),
    ]
