# Generated by Django 4.0 on 2022-03-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_game_date_created_result_date_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.IntegerField(verbose_name='number')),
                ('correct_value', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='option',
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='E4aKo3JG', max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='option',
            field=models.ManyToManyField(blank=True, to='website.NumberedValue'),
        ),
    ]
