# Generated by Django 4.0 on 2022-04-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_numberedvalue_remove_game_option_alter_user_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberedvalue',
            name='duration',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='oEG3fcPW', max_length=8, null=True, unique=True),
        ),
    ]
