# Generated by Django 4.0 on 2022-11-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_callrequest_alter_custom_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrequest',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterField(
            model_name='custom',
            name='code',
            field=models.CharField(blank=True, default='5d4Cg9Pf', max_length=8, null=True, unique=True),
        ),
    ]
