# Generated by Django 4.0 on 2022-04-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_numberedvalue_duration_alter_user_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='numberedvalue',
            name='duration',
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='8kqqUIAv', max_length=8, null=True, unique=True),
        ),
    ]
