# Generated by Django 4.0 on 2022-11-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_callrequest_options_alter_custom_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='custom',
            name='commissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='custom',
            name='code',
            field=models.CharField(blank=True, default='bwx9K7ny', max_length=8, null=True, unique=True),
        ),
    ]
