# Generated by Django 4.0 on 2022-07-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_userhistory_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='uBUYZKwU', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
