# Generated by Django 4.0 on 2022-04-25 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_delete_numbertime_result_duration_alter_user_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='9oRQnqpd', max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='numberedvalue',
            name='time_limit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.duration'),
        ),
    ]
