# Generated by Django 4.0 on 2022-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_duration_alter_user_code_numberedvalue_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='Efz1LsjL', max_length=8, null=True, unique=True),
        ),
    ]
