# Generated by Django 4.0 on 2022-07-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_user_code_alter_userhistory_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhistory',
            options={'verbose_name_plural': 'User Histories'},
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='xJmjY1Io', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='transaction',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=20, null=True),
        ),
    ]
