# Generated by Django 4.0 on 2022-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_userhistory_options_userhistory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='3QsPkD6z', max_length=8, null=True, unique=True),
        ),
    ]
