# Generated by Django 4.0 on 2022-07-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='R0LsqJGQ', max_length=8, null=True, unique=True),
        ),
    ]
