# Generated by Django 4.0 on 2022-07-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_userhistory_confirm_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='eaG5yxs9', max_length=8, null=True, unique=True),
        ),
    ]
