# Generated by Django 4.0 on 2022-04-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_result_duration_alter_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberedvalue',
            name='time_limit',
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='aJQlWD86', max_length=8, null=True, unique=True),
        ),
    ]
