# Generated by Django 4.0 on 2022-07-22 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0013_alter_paystack_email'),
        ('website', '0017_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='quRah7HT', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paystack.paystack'),
        ),
    ]
