# Generated by Django 4.0 on 2022-07-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_user_code_alter_userhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='jljLuRUv', max_length=8, null=True, unique=True),
        ),
    ]
