# Generated by Django 4.0 on 2022-07-22 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flutterwave', '0003_alter_flutterwave_generated'),
        ('website', '0019_userhistory_email_alter_user_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='user',
            new_name='paystack',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='flutterwave',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flutterwave.flutterwave'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='Mzu9wwd4', max_length=8, null=True, unique=True),
        ),
    ]
