# Generated by Django 4.0 on 2022-07-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_rename_user_userhistory_paystack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='WlY0XR2K', max_length=8, null=True, unique=True),
        ),
    ]
