# Generated by Django 4.0 on 2022-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='cGdw1IAJ', max_length=8, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
