# Generated by Django 4.0 on 2022-07-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_user_code_delete_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='JxA1m2aU', max_length=8, null=True, unique=True),
        ),
    ]
