# Generated by Django 4.0 on 2022-07-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_gameround_time_generated_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='33RKVGIi', max_length=8, null=True, unique=True),
        ),
    ]
