# Generated by Django 4.0 on 2022-07-31 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.gameround'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='time_generated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='oNUYqj7y', max_length=8, null=True, unique=True),
        ),
    ]
