# Generated by Django 4.0 on 2022-07-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_game_week_alter_gameround_time_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='NCd2rpcO', max_length=8, null=True, unique=True),
        ),
    ]
