# Generated by Django 4.0 on 2022-10-26 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremierLeagueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('name_acron', models.CharField(max_length=3)),
                ('win', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('skills', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PremierLeagueWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wk', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('wk',),
            },
        ),
        migrations.CreateModel(
            name='PremierLeagueFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('away_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('draw_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('homedraw_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('home_away_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('awaydraw_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('gg_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('ng_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('over_two', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('under_two', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('over_three', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('under_three', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('over_four', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('under_four', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('home_win', models.BooleanField(default=False)),
                ('away_win', models.BooleanField(default=False)),
                ('draw', models.BooleanField(default=False)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='virtual.premierleaguetable')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual.premierleaguetable')),
                ('wk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wks', to='virtual.premierleagueweek')),
            ],
        ),
        migrations.CreateModel(
            name='BetAccumulate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betid', models.CharField(max_length=20)),
                ('home', models.CharField(max_length=20)),
                ('away', models.CharField(max_length=20)),
                ('option', models.CharField(max_length=20)),
                ('odd', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('won', models.BooleanField(default=False)),
                ('loss', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.custom')),
            ],
        ),
    ]
