# Generated by Django 4.0 on 2022-10-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premierleaguefixture',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='premierleagueweek',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premierleagueweek',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
